services:
  metabase:
    image: metabase/metabase:latest
    container_name: agency_metabase
    env_file:
      - path: .env
        required: false
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - agency_internal_net
      - agency_analytics_net

networks:
  agency_internal_net:
    external: true
  agency_analytics_net:
    external: true
